ivit.client/ViewComponents/HeadViewComponent.cs
using ivit.client.Infrastructure.PageModelExtensions;
using Microsoft.AspNetCore.Mvc;

namespace ivit.client.ViewComponents
{
    public class HeadViewComponent : IvitViewComponent
    {
        public IViewComponentResult Invoke() => View();
    }
}

ivit.client/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@* ReSharper disable once MissingTitleTag *@
<head>
	<vc:Gtag></vc:Gtag>
	<vc:head></vc:head>
</head>

<body id="page-top">
<vc:Top></vc:Top>

<!-- ==========================
HEADER - START
=========================== -->
<vc:Header></vc:Header>
<!-- ==========================
HEADER - END
=========================== -->

<!-- ==========================
BODY - START
=========================== -->
@RenderBody()
<!-- ==========================
BODY - END
=========================== -->

<!-- ==========================
FOOTER - START
=========================== -->
<vc:Footer></vc:Footer>
<!-- ==========================
FOOTER - END
=========================== -->

@RenderSection("Scripts", false)
</body>
</html>

ivit.client/Pages/Shared/_LayoutLite.cshtml
<!DOCTYPE html>
<html>
@* ReSharper disable once MissingTitleTag *@
<head>
	<vc:Gtag></vc:Gtag>
	<vc:head></vc:head>
</head>

<body id="page-top">
    <vc:Top></vc:Top>

    <!-- ==========================
    NAV - START
    =========================== -->
    <vc:Navlite></vc:Navlite>
    <!-- ==========================
    NAV - END
    =========================== -->
    <!-- ==========================
    BODY - START
    =========================== -->
    @RenderBody()
    <!-- ==========================
    BODY - END
    =========================== -->
    <!-- ==========================
    FOOTER - START
    =========================== -->
    <vc:Footer></vc:Footer>
    <!-- ==========================
    FOOTER - END
    =========================== -->

    @RenderSection("Scripts", false)
</body>
</html>

ivit.client/Pages/Shared/_LayoutLiteLanguage.cshtml
<!DOCTYPE html>
<html>
@* ReSharper disable once MissingTitleTag *@
<head>
	<vc:Gtag></vc:Gtag>
	<vc:head></vc:head>
</head>

<body id="page-top">
<vc:Top></vc:Top>

<!-- ==========================
NAV - START
=========================== -->
<vc:Navlitelang></vc:Navlitelang>
<!-- ==========================
NAV - END
=========================== -->
<!-- ==========================
BODY - START
=========================== -->
@RenderBody()
<!-- ==========================
BODY - END
=========================== -->
<!-- ==========================
FOOTER - START
=========================== -->
<vc:Footer></vc:Footer>
<!-- ==========================
FOOTER - END
=========================== -->

@RenderSection("Scripts", false)
</body>
</html>