ivit.client/ViewModels/ProjectViewModel.cs
using System;

namespace ivit.client.ViewModels
{
	public class ProjectViewModel
	{
		public Guid Id { get; set; }
		public string Title { get; set; }
		public string LogoPath { get; set; }

	}
}

ivit.client/Pages/Cv.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ivit.client.Pages
{
    public class CvModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ivit.client/Pages/Index.cshtml.cs
using ivit.client.Infrastructure.PageModelExtensions;
using ivit.server.Services;

namespace ivit.client.Pages
{
	// ReSharper disable once ClassNeverInstantiated.Global
	public class IndexModel : IvitPageModel
	{
		public IndexModel(IContactEmailSender sender) : base(sender)
		{
		}

		public void OnGet()
		{
		}
	}
}

ivit.client/Pages/Portfolio.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ivit.client.Infrastructure.PageModelExtensions;
using ivit.client.ViewModels;
using ivit.db;
using ivit.db.Models;
using ivit.db.Repository;
using ivit.server.Services;
using Microsoft.AspNetCore.Hosting;

namespace ivit.client.Pages
{
	// ReSharper disable once ClassNeverInstantiated.Global
	public class PortfolioModel : IvitPageModel
	{
		private readonly IRepository<Project> _repository;
		private readonly IHostingEnvironment _env;

		public IEnumerable<PortfolioElementViewModel> Content { get; set; }

		public PortfolioModel(IContactEmailSender sender, IRepository<Project> repository, IHostingEnvironment env) : base(sender)
		{
			_repository = repository;
			_env = env;
		}

		public async Task OnGet()
		{
			var projectList = await _repository.FindAllAsync();
			var enumerableProjectList = projectList.ToList();

			var projects = enumerableProjectList.Where(p => p.EndDate == null).OrderBy(p => p.EndDate).ThenByDescending(p => p.StartDate).ToList();
			projects.AddRange(enumerableProjectList.Where(p => p.EndDate != null).OrderByDescending(p => p.EndDate));

			var model = new List<PortfolioElementViewModel>();
			var currentCulture = GetCulture();
			foreach (var project in projects)
			{
				var viewModel = new PortfolioElementViewModel
				{
					Id = project.Id,
					Title = project.Title,
					ShortDesc = currentCulture == "pl-Pl" ? project.ShortDescriptionPl : project.ShortDescription,
					Type = project.ProjectType
				};

				var logoPath = Path.Combine(_env.WebRootPath, "image", project.Id.ToString("D"), "logo.png");

				if (System.IO.File.Exists(logoPath))
				{
					viewModel.LogoPath = $"image/{project.Id:D}/logo.png";
				}
				else
				{
					switch (project.ProjectType)
					{
						case ProjectTypeEnum.Web:
							viewModel.LogoPath = "image/www.png";
							break;
						case ProjectTypeEnum.Desktop:
							viewModel.LogoPath = "image/desktop.png";
							break;
						case ProjectTypeEnum.Other:
							viewModel.LogoPath = "image/other.png";
							break;
						default:
							viewModel.LogoPath = "image/www.png";
							break;
					}
				}

				model.Add(viewModel);
			}

			Content = model;
		}
	}
}

ivit.client/Pages/Project.cshtml.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ivit.client.Infrastructure.PageModelExtensions;
using ivit.client.ViewModels;
using ivit.db;
using ivit.db.Models;
using ivit.db.Repository;
using ivit.server.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;

namespace ivit.client.Pages
{
	public class ProjectModel : IvitPageModel
	{
		public FullProjectViewModel Content { get; set; }
		public int ColumnsCounter { get; set; }

		private readonly IRepository<Project> _repository;
		private readonly IHostingEnvironment _env;

		public ProjectModel(IContactEmailSender sender, IRepository<Project> repository, IHostingEnvironment env) : base(sender)
		{
			_repository = repository;
			_env = env;
		}

		public async Task OnGet(Guid id)
		{
			var project = await _repository.GetSet()
				.Include(p => p.BackendTechnologies)
				.Include(p => p.FrontendTechnologies)
				.Include(p => p.Libraries)
				.Include(p => p.Others)
				.FirstOrDefaultAsync(p => p.Id == id);

			if (project != null)
			{
				var currentCulture = GetCulture();

				Content = new FullProjectViewModel
				{
					Role = currentCulture == "pl-PL" ? project.RolePl : project.Role,
					EndDate = project.EndDate.HasValue ? project.EndDate.Value.ToString("d") : currentCulture == "pl-PL" ? "teraz" : "now",
					LongDescription = currentCulture == "pl-PL" ? project.LongDescriptionPl : project.LongDescription,
					ShortDescription = currentCulture == "pl-PL" ? project.ShortDescriptionPl : project.ShortDescription,
					StartDate = project.StartDate.ToString("d"),
					Title = project.Title,
					Type = project.ProjectType.ToString()
				};

				//LOGO PART
				var logoPath = Path.Combine(_env.WebRootPath, "image", project.Id.ToString("D"), "logo.png");
				if (System.IO.File.Exists(logoPath))
				{
					Content.LogoFileName = $"image/{project.Id:D}/logo.png";
				}
				else
				{
					switch (project.ProjectType)
					{
						case ProjectTypeEnum.Web:
							Content.LogoFileName = "image/www.png";
							break;
						case ProjectTypeEnum.Desktop:
							Content.LogoFileName = "image/desktop.png";
							break;
						case ProjectTypeEnum.Other:
							Content.LogoFileName = "image/other.png";
							break;
						default:
							Content.LogoFileName = "image/www.png";
							break;
					}
				}

				//SCREENS PART
				var pathScreens = Path.Combine(_env.WebRootPath, "image", project.Id.ToString("D"));
				var dirScreens = new DirectoryInfo(pathScreens);

				if (dirScreens.Exists && dirScreens.EnumerateFiles().Any(p => p.Name != "logo.png"))
				{
					Content.ScreensFileName = dirScreens.EnumerateFiles().Where(p => p.Name != "logo.png").Select(screen => $"image/{project.Id:D}/{screen.Name}").ToList();
				}

				ColumnsCounter = 0;

				//BACKEND PART
				Content.BackendTechnologies = project.BackendTechnologies
					.Select(p => currentCulture == "pl-PL" ? p.DescriptionPl : p.Description).ToList();

				if (Content.BackendTechnologies.Any()) ColumnsCounter++;

				//FRONTEND PART
				Content.FrontendTechnologies = project.FrontendTechnologies
					.Select(p => currentCulture == "pl-PL" ? p.DescriptionPl : p.Description).ToList();

				if (Content.FrontendTechnologies.Any()) ColumnsCounter++;

				//LIBRARY PART
				Content.Libraries = project.Libraries
					.Select(p => currentCulture == "pl-PL" ? p.DescriptionPl : p.Description).ToList();

				if (Content.Libraries.Any()) ColumnsCounter++;

				//OTHER PART
				Content.Others = project.Others
					.Select(p => currentCulture == "pl-PL" ? p.DescriptionPl : p.Description).ToList();

				if (Content.Others.Any()) ColumnsCounter++;

			}
		}
	}
}

ivit.client/Pages/Resume.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ivit.client.Pages
{
    public class ResumeModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ivit.client/ViewComponents/TitleViewComponent.cs
using ivit.client.Infrastructure.PageModelExtensions;
using ivit.client.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ivit.client.ViewComponents
{
	public class TitleViewComponent : IvitViewComponent
	{
		public ProjectTitleViewModel Content { get; set; }

		// ReSharper disable once EmptyConstructor
		public TitleViewComponent()
		{
		}

		public IViewComponentResult Invoke(string title, string imagePath)
		{
			Content = new ProjectTitleViewModel
			{
				Title = title,
				LogoPath = imagePath
			};
			return View(this);
		}
	}
}

ivit.client/Pages/Cv.cshtml
@page
@model ivit.client.Pages.CvModel
@{
    Layout = "_LayoutLite";
    ViewData["Title"] = "Cv";
}

<h2>Cv</h2>
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />
DUPA<br />

ivit.client/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@model IndexModel
@inject IHtmlLocalizer<IndexModel> Localizer

@{
	ViewData["Title"] = Localizer["Title"];
}

<!-- ==========================
ABOUT - START
=========================== -->
<vc:About></vc:About>
<!-- ==========================
ABOUT - END
=========================== -->
<!-- ==========================
SERVICES - START
=========================== -->
<vc:Services></vc:Services>
<!-- ==========================
SERVICES - END
=========================== -->
<!-- ==========================
NUMBERS - START
=========================== -->
<vc:Numbers></vc:Numbers>
<!-- ==========================
NUMBERS - END
=========================== -->
<!-- ==========================
REFERENCE - START
=========================== -->
<vc:Reference></vc:Reference>
<!-- ==========================
REFERENCE - END
=========================== -->
<!-- ==========================
PRICING - START
=========================== -->
<vc:Resume></vc:Resume>
<!-- ==========================
PRICING - END
=========================== -->
<!-- ==========================
CONTACT - START
=========================== -->
<vc:Contact></vc:Contact>
<!-- ==========================
CONTACT - END
=========================== -->

ivit.client/Pages/Portfolio.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@model ivit.client.Pages.PortfolioModel
@inject IHtmlLocalizer<PortfolioModel> Localizer

@{
	Layout = "_LayoutLiteLanguage";
	ViewData["Title"] = Localizer["Portfolio"];
	var projectCounter = 0;
}

<section id="pricing" class="content-first">
	<div class="container">
		<h2 class="scrollpoint sp-effect3">@Localizer["Portfolio"]</h2>
		<p>@Localizer["ShortDescription"]</p>
	</div>
</section>
<section class="content-second">
	<ul class="grid cs-style-4">
		@foreach (var project in Model.Content)
		{
			var figureCounter = projectCounter % 4;
			var figureClass = figureCounter == 0
				? "scrollpoint sp-effect4" : figureCounter == 1
					? "scrollpoint sp-effect3" : figureCounter == 2
						? "scrollpoint sp-effect2" : "scrollpoint sp-effect1";
			<li>
				<figure class="@figureClass">
					<div>
						<img src="@project.LogoPath" alt="img04">
					</div>
					<figcaption>
						<h3>@project.Title</h3>
						<a asp-page="Project" asp-route-id="@project.Id">@Localizer["ShowMe"]</a>
					</figcaption>
				</figure>
			</li>
			projectCounter++;
		}
	</ul>
</section>

ivit.client/Pages/Project.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@model ProjectModel
@inject IHtmlLocalizer<ProjectModel> Localizer

@{
	Layout = "_LayoutLiteLanguage";
	ViewData["Title"] = Model.Content.Title;
}

<header>
	@await Component.InvokeAsync("Title", new { title = Model.Content.Title, imagePath = Model.Content.LogoFileName })
</header>

<section id="description" class="content-second">
	<div class="container">
		<h3>@Model.Content.LongDescription</h3>
	</div>
</section>

<section id="separator" class="content-first">
	<div class="container">
		<div class="row scrollpoint sp-effect3">
			<div class="col-sm-4">
				<i class="fa fa-file-code-o"></i>
				<p>@Localizer["ProjectType"] <b>@Model.Content.Type</b></p>
			</div>
			<div class="col-sm-4">
				<i class="fa fa-calendar"></i>
				<p>@Localizer["ProjectDate"] <b>@Model.Content.StartDate - @Model.Content.EndDate</b></p>
			</div>
			<div class="col-sm-4">
				<i class="fa fa-user"></i>
				<p>@Localizer["ProjectRole"] <b>@Model.Content.Role</b></p>
			</div>
		</div>
	</div>
</section>

@switch (Model.ColumnsCounter)
{
	case 1:
		{
			<section class="content-second">
				<div class="container">
					@if (Model.Content.BackendTechnologies.Any())
					{
						<div class="col-sm-12">
							<h3>@Localizer["Backend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.BackendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Libraries.Any())
					{
						<div class="col-sm-12">
							<h3>@Localizer["Libraries"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Libraries)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.FrontendTechnologies.Any())
					{
						<div class="col-sm-12">
							<h3>@Localizer["Frontend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.FrontendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Others.Any())
					{
						<div class="col-sm-12">
							<h3>@Localizer["Other"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Others)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
				</div>
			</section>
			break;
		}
	case 2:
		{
			<section class="content-second">
				<div class="container">
					@if (Model.Content.BackendTechnologies.Any())
					{
						<div class="col-sm-6">
							<h3>@Localizer["Backend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.BackendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Libraries.Any())
					{
						<div class="col-sm-6">
							<h3>@Localizer["Libraries"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Libraries)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.FrontendTechnologies.Any())
					{
						<div class="col-sm-6">
							<h3>@Localizer["Frontend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.FrontendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Others.Any())
					{
						<div class="col-sm-6">
							<h3>@Localizer["Other"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Others)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
				</div>
			</section>
			break;
		}
	case 3:
		{
			<section class="content-second">
				<div class="container">
					@if (Model.Content.BackendTechnologies.Any())
					{
						<div class="col-sm-4">
							<h3>@Localizer["Backend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.BackendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Libraries.Any())
					{
						<div class="col-sm-4">
							<h3>@Localizer["Libraries"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Libraries)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.FrontendTechnologies.Any())
					{
						<div class="col-sm-4">
							<h3>@Localizer["Frontend"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.FrontendTechnologies)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
					@if (Model.Content.Others.Any())
					{
						<div class="col-sm-4">
							<h3>@Localizer["Other"]</h3>
							<ul>
								@foreach (var listElement in Model.Content.Others)
								{
									<li>
										@listElement
									</li>
								}
							</ul>
						</div>
					}
				</div>
			</section>
			break;
		}
	case 4:
		{
			<section class="content-second">
				<div class="container">
					<div class="col-sm-3">
						<h3>@Localizer["Backend"]</h3>
						<ul>
							@foreach (var listElement in Model.Content.BackendTechnologies)
							{
								<li>
									@listElement
								</li>
							}
						</ul>
					</div>
					<div class="col-sm-3">
						<h3>@Localizer["Libraries"]</h3>
						<ul>
							@foreach (var listElement in Model.Content.Libraries)
							{
								<li>
									@listElement
								</li>
							}
						</ul>
					</div>
					<div class="col-sm-3">
						<h3>@Localizer["Frontend"]</h3>
						<ul>
							@foreach (var listElement in Model.Content.FrontendTechnologies)
							{
								<li>
									@listElement
								</li>
							}
						</ul>
					</div>
					<div class="col-sm-3">
						<h3>@Localizer["Other"]</h3>
						<ul>
							@foreach (var listElement in Model.Content.Others)
							{
								<li>
									@listElement
								</li>
							}
						</ul>
					</div>
				</div>
			</section>
			break;
		}
}


@if (Model.Content.ScreensFileName != null)
{
	<section id="screenshots" class="content-first">
		<div class="container">
			<h2>@Localizer["Screenshots"]</h2>
			<div id="screenCarousel" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					@for (var i = 0; i < Model.Content.ScreensFileName.Count; i++)
					{
						if (i == 0)
						{
							<li data-target="#screenCarousel" data-slide-to="@i" class="active"></li>
						}
						else
						{
							<li data-target="#screenCarousel" data-slide-to="@i"></li>
						}

					}
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner">
					@for (var i = 0; i < Model.Content.ScreensFileName.Count; i++)
					{
						if (i == 0)
						{
							<div class="item active">
								<img src="@Model.Content.ScreensFileName[i]" alt="">
							</div>
						}
						else
						{
							<div class="item">
								<img src="@Model.Content.ScreensFileName[i]" alt="">
							</div>
						}
					}
				</div>

				<!-- Left and right controls -->
				<a class="left carousel-control" href="#screenCarousel" data-slide="prev"><i class="fa fa-arrow-left"></i></a>
				<a class="right carousel-control" href="#screenCarousel" data-slide="next"><i class="fa fa-arrow-right"></i></a>
			</div>
		</div>
	</section>
}

ivit.client/Pages/Resume.cshtml
@page
@model ivit.client.Pages.ResumeModel
@{
	Layout = "_LayoutLite";
	ViewData["Title"] = "Resume";
}

<h2>Resume</h2>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>
DUPA<br/>DUPA<br/>